GET http://localhost:3000/

### GET /items
GET http://localhost:3000/items

### GET /items/:id
GET http://localhost:3000/items/5

### POST /items
POST http://localhost:3000/items
content-type: application/json

{"name": "nimi2"}

### DELETE /items/:id
DELETE http://localhost:3000/items/5

### PUT /items/:id
PUT http://localhost:3000/items/5
content-type: application/json

{"name": "Uus nimi"}

### POST /items error
POST http://localhost:3000/items

{"jotai": "jotai"}